spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: derivdima@gmail.com
    password: kldk tzcj gdac bvmp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: MjAwNDE4MzA0MjgwcGFrYXlhMjAwNDE4MzA0MjgwcGFrYXlh

aws:
  s3:
    bucketName: e-commerce-onlineshopping
    access: "AKIA2LIP2C3U3LN5YMAJ"
    secret: "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"

stripe:
  secret-key: sk_test_51R4PVXRjYuUozJvdsLK1ovgCJO9BzygGoHnwyXPI2BIK8BU0PYa6KyydV22tTNn4xdUNO3pxaw59FBUsTaHwOfv500yKf11Ttr